const mongoose = require('mongoose');
const {  Types, Schema, model } = mongoose;

const FoodEntrySchema = new Schema({
  employeeId: { type: Types.ObjectId, ref: 'Employee', required: true },
  foodStatus: { type: String, enum: ['utilized', 'wasted', 'not_need'], required: true },
  firstName: { type: String, required: true },
  lastName: { type: String, required: true },
  photoUrl: {type: String},
  email : { type: String, required: true },
}, { _id: false });

const GuestSchema = new Schema({
  name: { type: String, required: true }
}, { _id: false });

const FoodRecordSchema = new Schema({
  date: { type: Date, required: true },
  totalFood: { type: Number, required: true },
  mealType: { 
    type: String, 
    enum: ['breakfast', 'lunch', 'dinner', 'evening_snacks', 'midnight_snacks'], 
    required: true 
  },
  mealRate: { type: Number, required: true },
  cost: { type: Number, required: true },
  entries: { type: [FoodEntrySchema], default: [] },
  guests: { type: [GuestSchema], default: [] },
  isAutoGenerated : {type: Boolean, default: false},
  createdBy: { type: Types.ObjectId, ref: 'Employee' },
}, { 
  timestamps: true 
});

// Add compound unique index - THIS IS CRUCIAL
FoodRecordSchema.index({ date: 1, mealType: 1 }, { unique: true });

module.exports = model('FoodRecord', FoodRecordSchema);